linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - err113
    - gofmt
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - unconvert
    - unparam
    - unused
    - whitespace

  # don't enable:
  # - asciicheck
  # - depguard
  # - exportloopref
  # - funlen
  # - gochecknoglobals
  # - gocognit
  # - godox
  # - gofmt
  # - goheader
  # - gomodguard
  # - goprintffuncname
  # - interfacer
  # - maligned
  # - nestif
  # - prealloc
  # - rowserrcheck
  # - stylecheck
  # - typecheck
  # - whitespace
  # - wsl

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - style
      - performance
    disabled-checks:
      - whyNoLint
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
